2020-08-21 13:02:03.935 [error] <0.552.0> gen_server <0.552.0> terminated with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => order_id,message => nil,module => nil,reason => nil},[{nil,order_id,[],[]},{'Elixir.ExchangeApiWeb.OrderLive','-render/1-fun-0-',2,[{file,"lib/exchange_api_web/live/order_live.html.leex"},{line,2}]},{'Elixir.Phoenix.LiveView.Diff',traverse,5,[{file,"lib/phoenix_live_view/diff.ex"},{line,250}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/5-fun-0-',3,[{file,"lib/phoenix_live_view/diff.ex"},...]},...]}
2020-08-21 13:02:03.955 [error] <0.552.0> CRASH REPORT Process <0.552.0> with 0 neighbours crashed with reason: {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => order_id,message => nil,module => nil,reason => nil},[{nil,order_id,[],[]},{'Elixir.ExchangeApiWeb.OrderLive','-render/1-fun-0-',2,[{file,"lib/exchange_api_web/live/order_live.html.leex"},{line,2}]},{'Elixir.Phoenix.LiveView.Diff',traverse,5,[{file,"lib/phoenix_live_view/diff.ex"},{line,250}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/5-fun-0-',3,[{file,"lib/phoenix_live_view/diff.ex"},...]},...]}
2020-08-21 13:02:03.955 [error] <0.432.0> Supervisor {<0.432.0>,'Elixir.Supervisor.Default'} had child undefined started with {'Elixir.Phoenix.LiveView.Channel',start_link,undefined} at <0.552.0> exit with reason {#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 0,function => order_id,message => nil,module => nil,reason => nil},[{nil,order_id,[],[]},{'Elixir.ExchangeApiWeb.OrderLive','-render/1-fun-0-',2,[{file,"lib/exchange_api_web/live/order_live.html.leex"},{line,2}]},{'Elixir.Phoenix.LiveView.Diff',traverse,5,[{file,"lib/phoenix_live_view/diff.ex"},{line,250}]},{'Elixir.Phoenix.LiveView.Diff','-traverse_dynamic/5-fun-0-',3,[{file,"lib/phoenix_live_view/diff.ex"},...]},...]} in context child_terminated
2020-08-21 13:05:56.720 [error] <0.590.0> CRASH REPORT Process <0.590.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_integer,[<<"10ER039584">>],[]},{'Elixir.ExchangeApiWeb.OrderLive',mount,3,[{file,"lib/exchange_api_web/live/order_live.ex"},{line,9}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,256}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',5,[{file,"lib/phoenix_live_view/static.ex"},{line,302}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...},...}
2020-08-21 13:05:56.735 [error] <0.590.0> Cowboy stream 8 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.557.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,binary_to_integer,[<<"10ER039584">>],[]},{'Elixir.ExchangeApiWeb.OrderLive',mount,3,[{file,"lib/exchange_api_web/live/order_live.ex"},{line,9}]},{'Elixir.Phoenix.LiveView.Utils','maybe_call_mount!',3,[{file,"lib/phoenix_live_view/utils.ex"},{line,256}]},{'Elixir.Phoenix.LiveView.Static','call_mount_and_handle_params!',5,[{file,"lib/phoenix_live_view/static.ex"},{line,302}]},{'Elixir.Phoenix.LiveView.Static',...},...]},...},...}
2020-08-26 10:44:26.196 [error] <0.826.0> CRASH REPORT Process <0.826.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"could not lookup Ecto repo ExchangeApi.Repo because it was not started or it does not exist">>},[{'Elixir.Ecto.Repo.Registry',lookup,1,[{file,"lib/ecto/repo/registry.ex"},{line,19}]},{'Elixir.Ecto.Repo.Schema',do_insert,4,[{file,"lib/ecto/repo/schema.ex"},{line,211}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,15}]},{'Elixir.ExchangeApiWeb.UserController',...},...]},...},...},...}
2020-08-26 10:44:26.220 [error] <0.826.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.825.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"could not lookup Ecto repo ExchangeApi.Repo because it was not started or it does not exist">>},[{'Elixir.Ecto.Repo.Registry',lookup,1,[{file,"lib/ecto/repo/registry.ex"},{line,19}]},{'Elixir.Ecto.Repo.Schema',do_insert,4,[{file,"lib/ecto/repo/schema.ex"},{line,211}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,15}]},{'Elixir.ExchangeApiWeb.UserController',...},...]},...},...}
2020-08-26 10:45:06.038 [error] <0.632.0> CRASH REPORT Process <0.632.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.CastError',message => <<"expected params to be a map with atoms or string keys, got a map with mixed keys: %{:jwt => \"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGNoYW5nZV9hcGkiLCJleHAiOjE2MDA4NTQzMDUsImlhdCI6MTU5ODQzNTEwNSwiaXNzIjoiZXhjaGFuZ2VfYXBpIiwianRpIjoiYThmMTc3M2UtMGFmYS00MTI3LWFkNmQtMmFiOTc3MmJmMGRjIiwibmJmIjoxNTk4NDM1MTA0LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.1lR5KzoiLzmu-cLrAB0lbs4UCT4To86f6pF-m6LwjxuV4nOKHyJHBcCS6mP...">>,...},...},...},...},...}
2020-08-26 10:45:06.058 [error] <0.632.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.631.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.CastError',message => <<"expected params to be a map with atoms or string keys, got a map with mixed keys: %{:jwt => \"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGNoYW5nZV9hcGkiLCJleHAiOjE2MDA4NTQzMDUsImlhdCI6MTU5ODQzNTEwNSwiaXNzIjoiZXhjaGFuZ2VfYXBpIiwianRpIjoiYThmMTc3M2UtMGFmYS00MTI3LWFkNmQtMmFiOTc3MmJmMGRjIiwibmJmIjoxNTk4NDM1MTA0LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.1lR5KzoiLzmu-cLrAB0lbs4UCT4To86f6pF-m6LwjxuV4nOKHyJHBcCS6mPI6...">>,...},...},...},...}
2020-08-26 10:46:03.693 [error] <0.634.0> CRASH REPORT Process <0.634.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,2,[{file,"lib/exchange_api_web/c..."},...]},...]},...},...},...}
2020-08-26 10:46:03.694 [error] <0.634.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.631.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,2,[{file,"lib/exchange_api_web/con..."},...]},...]},...},...}
2020-08-26 10:46:24.789 [error] <0.684.0> CRASH REPORT Process <0.684.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,2,[{file,"lib/exchange_api_web/c..."},...]},...]},...},...},...}
2020-08-26 10:46:24.792 [error] <0.684.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.631.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,2,[{file,"lib/exchange_api_web/con..."},...]},...]},...},...}
2020-08-26 10:47:43.935 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,2,[{file,"lib/exchange_api_web/c..."},...]},...]},...},...},...}
2020-08-26 10:47:43.936 [error] <0.688.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.687.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Conn.AlreadySentError',message => <<"the response was already sent">>},[{'Elixir.Plug.Conn',resp,3,[{file,"lib/plug/conn.ex"},{line,583}]},{'Elixir.Plug.Conn',send_resp,3,[{file,"lib/plug/conn.ex"},{line,559}]},{'Elixir.ExchangeApiWeb.UserController',action,2,[{file,"lib/exchange_api_web/controllers/user_controller.ex"},{line,1}]},{'Elixir.ExchangeApiWeb.UserController',phoenix_controller_pipeline,2,[{file,"lib/exchange_api_web/con..."},...]},...]},...},...}
2020-08-26 10:52:25.746 [error] <0.844.0> CRASH REPORT Process <0.844.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-08-26 10:52:25.746 [error] <0.844.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.843.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-08-26 10:56:04.899 [error] <0.966.0> CRASH REPORT Process <0.966.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.CastError',message => <<"expected params to be a :map, got: `[jwt: \"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGNoYW5nZV9hcGkiLCJleHAiOjE2MDA4NTQ5NjQsImlhdCI6MTU5ODQzNTc2NCwiaXNzIjoiZXhjaGFuZ2VfYXBpIiwianRpIjoiMWY0OWE3NWUtZjIxNy00ZjYwLTg4M2ItMzllN2EwMmM5NDRiIiwibmJmIjoxNTk4NDM1NzYzLCJzdWIiOiIxMyIsInR5cCI6ImFjY2VzcyJ9.vAmbYguS4_wNVBH-JrdCICNTEWwILZYCxcPC2YcaLjCAofkH1HPSXJ-K5DGQ_-ubZ-IQfu2PviD-ri9moPH-EQ\"]`">>,type => map,...},...},...},...},...}
2020-08-26 10:56:04.922 [error] <0.966.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.965.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Ecto.CastError',message => <<"expected params to be a :map, got: `[jwt: \"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGNoYW5nZV9hcGkiLCJleHAiOjE2MDA4NTQ5NjQsImlhdCI6MTU5ODQzNTc2NCwiaXNzIjoiZXhjaGFuZ2VfYXBpIiwianRpIjoiMWY0OWE3NWUtZjIxNy00ZjYwLTg4M2ItMzllN2EwMmM5NDRiIiwibmJmIjoxNTk4NDM1NzYzLCJzdWIiOiIxMyIsInR5cCI6ImFjY2VzcyJ9.vAmbYguS4_wNVBH-JrdCICNTEWwILZYCxcPC2YcaLjCAofkH1HPSXJ-K5DGQ_-ubZ-IQfu2PviD-ri9moPH-EQ\"]`">>,type => map,value => ...},...},...},...}
2020-08-26 10:56:19.059 [error] <0.1016.0> CRASH REPORT Process <0.1016.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-08-26 10:56:19.062 [error] <0.1016.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.965.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-08-26 11:01:27.316 [error] <0.1282.0> CRASH REPORT Process <0.1282.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-08-26 11:01:27.316 [error] <0.1282.0> Cowboy stream 3 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1171.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-08-26 11:04:40.988 [error] <0.1336.0> CRASH REPORT Process <0.1336.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 56842,message => nil,postgres => #{code => string_data_right_truncation,file => <<"varchar.c">>,line => <<"636">>,message => <<"value too long for type character varying(255)">>,pg_code => <<"22001">>,routine => <<"varchar">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => nil},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,593}]},{'Elixir.Ecto.Repo.Schema',...},...]},...},...},...}
2020-08-26 11:04:40.989 [error] <0.1336.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1335.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 56842,message => nil,postgres => #{code => string_data_right_truncation,file => <<"varchar.c">>,line => <<"636">>,message => <<"value too long for type character varying(255)">>,pg_code => <<"22001">>,routine => <<"varchar">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => nil},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,593}]},{'Elixir.Ecto.Repo.Schema',...},...]},...},...}
2020-08-26 11:10:09.936 [error] <0.1395.0> CRASH REPORT Process <0.1395.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"lusddid2s@bar.com">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controll..."},...]},...]},...},...},...}
2020-08-26 11:10:09.937 [error] <0.1395.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1394.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"argument error">>},[{erlang,apply,[<<"lusddid2s@bar.com">>,id,[]],[]},{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/controller..."},...]},...]},...},...}
2020-08-26 11:13:34.835 [error] <0.1448.0> CRASH REPORT Process <0.1448.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{<<"email">> => <<"lusddid2ddds@bar.com">>,<<"jwt">> => <<>>}},[{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web..."},...]},...]},...},...},...}
2020-08-26 11:13:34.836 [error] <0.1448.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1447.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => id,message => nil,term => #{<<"email">> => <<"lusddid2ddds@bar.com">>,<<"jwt">> => <<>>}},[{'Elixir.ExchangeApi.Guardian',subject_for_token,2,[{file,"lib/exchange_api/guardian.ex"},{line,6}]},{'Elixir.Guardian',returning_tuple,1,[{file,"lib/guardian.ex"},{line,756}]},{'Elixir.Guardian',encode_and_sign,4,[{file,"lib/guardian.ex"},{line,578}]},{'Elixir.ExchangeApiWeb.UserController',create,2,[{file,"lib/exchange_api_web/c..."},...]},...]},...},...}
2020-08-26 11:13:58.487 [error] <0.1498.0> CRASH REPORT Process <0.1498.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 56839,message => nil,postgres => #{code => string_data_right_truncation,file => <<"varchar.c">>,line => <<"636">>,message => <<"value too long for type character varying(255)">>,pg_code => <<"22001">>,routine => <<"varchar">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => nil},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,593}]},{'Elixir.Ecto.Repo.Schema',...},...]},...},...},...}
2020-08-26 11:13:58.488 [error] <0.1498.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.1447.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 56839,message => nil,postgres => #{code => string_data_right_truncation,file => <<"varchar.c">>,line => <<"636">>,message => <<"value too long for type character varying(255)">>,pg_code => <<"22001">>,routine => <<"varchar">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => nil},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,"lib/ecto/adapters/sql.ex"},{line,593}]},{'Elixir.Ecto.Repo.Schema',...},...]},...},...}
2020-08-26 11:21:18.393 [error] <0.622.0> CRASH REPORT Process <0.622.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-08-26 11:21:18.422 [error] <0.622.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.621.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-08-26 11:24:18.354 [error] <0.626.0> CRASH REPORT Process <0.626.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    ...">>,...},...},...},...},...}
2020-08-26 11:24:18.357 [error] <0.626.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.625.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<"Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @d...">>,...},...},...},...}
2020-08-26 11:43:28.606 [error] <0.748.0> CRASH REPORT Process <0.748.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-GB,en-US;q=0....">>,...},...}},...},...},...},...},...},...}
2020-08-26 11:43:28.607 [error] <0.748.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.747.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-GB,en-US;q=0.9,...">>,...},...}},...},...},...},...},...}
2020-08-26 11:43:43.445 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-GB,en-US;q=0....">>,...},...}},...},...},...},...},...},...}
2020-08-26 11:43:43.445 [error] <0.812.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.747.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-GB,en-US;q=0.9,...">>,...},...}},...},...},...},...},...}
2020-08-26 11:44:43.638 [error] <0.817.0> CRASH REPORT Process <0.817.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"authorization">> => <<"Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGNoYW5nZV9hcGkiLCJleHAiOjE2MDA4NTY2ODEsImlhdCI6MTU5ODQzNzQ4MSwiaXNzIjoiZXhjaGFuZ2V...">>,...},...}},...},...},...},...},...},...}
2020-08-26 11:44:43.638 [error] <0.817.0> Cowboy stream 1 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.816.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"authorization">> => <<"Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJleGNoYW5nZV9hcGkiLCJleHAiOjE2MDA4NTY2ODEsImlhdCI6MTU5ODQzNzQ4MSwiaXNzIjoiZXhjaGFuZ2VfY...">>,...},...}},...},...},...},...},...}
2020-08-26 11:45:11.019 [error] <0.820.0> CRASH REPORT Process <0.820.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"ecb4116b-4c13-49d7-bccf-d5cc59ac9c3...">>,...},...}},...},...},...},...},...},...}
2020-08-26 11:45:11.025 [error] <0.820.0> Cowboy stream 2 with ranch listener 'Elixir.ExchangeApiWeb.Endpoint.HTTP' and connection process <0.816.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"*/*">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"connection">> => <<"keep-alive">>,<<"content-length">> => <<"0">>,<<"host">> => <<"localhost:4000">>,<<"postman-token">> => <<"ecb4116b-4c13-49d7-bccf-d5cc59ac9c37">>,...},...}},...},...},...},...},...}
